CREATE TABLE IF NOT EXISTS "order" (
    -- @Id ve @GeneratedValue(strategy = GenerationType.IDENTITY)
    -- Bu, tablonun anahtarını (Primary Key) oluşturur ve otomatik olarak artmasını sağlar.
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- private LocalDateTime creationTime
    -- Tarih ve saati tutar. TIMESTAMP çoğu RDBMS için uygun tiptir.
                         creation_time TIMESTAMP WITHOUT TIME ZONE,

    -- private String orderNumber
    -- Değişken uzunlukta metin (String) tutar. Uzunluk tahmini bir değerdir.
                         order_number VARCHAR(255)
);